version: '3.8'
services:
  database:
    container_name: microservices-database
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 10s
      retries: 20
  user:
    image: store/users
    ports:
      - 8080:8080
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_URL: jdbc:postgresql://database:5432/dev
    depends_on:
      database:
        condition: service_healthy
  product:
    image: store/products
    ports:
      - 8081:8081
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_URL: jdbc:postgresql://database:5432/dev
    depends_on:
      database:
        condition: service_healthy
  cart:
    image: store/cart
    ports:
      - 8082:8082
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_URL: jdbc:postgresql://database:5432/dev
    depends_on:
      database:
        condition: service_healthy
